# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - konkamon-strapi

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "20.17.0"

      - name: npm install, build, and test
        env:
          NODE_ENV : production
        run: |
          npm install
          npm run build
          npm run test --if-present

      - name: Create Archive of application code
        run: |
          mkdir -p zip
          zip  -r app.zip . -x@.zipignore

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: strapi-app
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: strapi-app

      - name: Unzip artifact for deployment
        run: unzip app.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6E2955F4E9724E0FA46C0548EC536B07 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3F7C95978DE9406B8903B6495355F721 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DA23C8DA8B9B453985C8D2E713277E1C }}

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "konkamon-strapi"
          slot-name: "Production"
          package: .
